//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha4

import (
	unsafe "unsafe"

	v1beta1 "github.com/inspur-ics/cluster-api-provider-ics/api/v1beta1"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterModule)(nil), (*v1beta1.ClusterModule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ClusterModule_To_v1beta1_ClusterModule(a.(*ClusterModule), b.(*v1beta1.ClusterModule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterModule)(nil), (*ClusterModule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterModule_To_v1alpha4_ClusterModule(a.(*v1beta1.ClusterModule), b.(*ClusterModule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiskSpec)(nil), (*v1beta1.DiskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_DiskSpec_To_v1beta1_DiskSpec(a.(*DiskSpec), b.(*v1beta1.DiskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DiskSpec)(nil), (*DiskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DiskSpec_To_v1alpha4_DiskSpec(a.(*v1beta1.DiskSpec), b.(*DiskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSCluster)(nil), (*v1beta1.ICSCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSCluster_To_v1beta1_ICSCluster(a.(*ICSCluster), b.(*v1beta1.ICSCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSCluster)(nil), (*ICSCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSCluster_To_v1alpha4_ICSCluster(a.(*v1beta1.ICSCluster), b.(*ICSCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSClusterList)(nil), (*v1beta1.ICSClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSClusterList_To_v1beta1_ICSClusterList(a.(*ICSClusterList), b.(*v1beta1.ICSClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSClusterList)(nil), (*ICSClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSClusterList_To_v1alpha4_ICSClusterList(a.(*v1beta1.ICSClusterList), b.(*ICSClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSClusterSpec)(nil), (*v1beta1.ICSClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSClusterSpec_To_v1beta1_ICSClusterSpec(a.(*ICSClusterSpec), b.(*v1beta1.ICSClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSClusterSpec)(nil), (*ICSClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSClusterSpec_To_v1alpha4_ICSClusterSpec(a.(*v1beta1.ICSClusterSpec), b.(*ICSClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSClusterStatus)(nil), (*v1beta1.ICSClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSClusterStatus_To_v1beta1_ICSClusterStatus(a.(*ICSClusterStatus), b.(*v1beta1.ICSClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSClusterStatus)(nil), (*ICSClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSClusterStatus_To_v1alpha4_ICSClusterStatus(a.(*v1beta1.ICSClusterStatus), b.(*ICSClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSIdentityReference)(nil), (*v1beta1.ICSIdentityReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSIdentityReference_To_v1beta1_ICSIdentityReference(a.(*ICSIdentityReference), b.(*v1beta1.ICSIdentityReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSIdentityReference)(nil), (*ICSIdentityReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSIdentityReference_To_v1alpha4_ICSIdentityReference(a.(*v1beta1.ICSIdentityReference), b.(*ICSIdentityReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachine)(nil), (*v1beta1.ICSMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachine_To_v1beta1_ICSMachine(a.(*ICSMachine), b.(*v1beta1.ICSMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachine)(nil), (*ICSMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachine_To_v1alpha4_ICSMachine(a.(*v1beta1.ICSMachine), b.(*ICSMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineList)(nil), (*v1beta1.ICSMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineList_To_v1beta1_ICSMachineList(a.(*ICSMachineList), b.(*v1beta1.ICSMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineList)(nil), (*ICSMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineList_To_v1alpha4_ICSMachineList(a.(*v1beta1.ICSMachineList), b.(*ICSMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineSpec)(nil), (*v1beta1.ICSMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec(a.(*ICSMachineSpec), b.(*v1beta1.ICSMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineSpec)(nil), (*ICSMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec(a.(*v1beta1.ICSMachineSpec), b.(*ICSMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineStatus)(nil), (*v1beta1.ICSMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineStatus_To_v1beta1_ICSMachineStatus(a.(*ICSMachineStatus), b.(*v1beta1.ICSMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineStatus)(nil), (*ICSMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineStatus_To_v1alpha4_ICSMachineStatus(a.(*v1beta1.ICSMachineStatus), b.(*ICSMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineTemplate)(nil), (*v1beta1.ICSMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineTemplate_To_v1beta1_ICSMachineTemplate(a.(*ICSMachineTemplate), b.(*v1beta1.ICSMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineTemplate)(nil), (*ICSMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineTemplate_To_v1alpha4_ICSMachineTemplate(a.(*v1beta1.ICSMachineTemplate), b.(*ICSMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineTemplateList)(nil), (*v1beta1.ICSMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineTemplateList_To_v1beta1_ICSMachineTemplateList(a.(*ICSMachineTemplateList), b.(*v1beta1.ICSMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineTemplateList)(nil), (*ICSMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineTemplateList_To_v1alpha4_ICSMachineTemplateList(a.(*v1beta1.ICSMachineTemplateList), b.(*ICSMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineTemplateResource)(nil), (*v1beta1.ICSMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineTemplateResource_To_v1beta1_ICSMachineTemplateResource(a.(*ICSMachineTemplateResource), b.(*v1beta1.ICSMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineTemplateResource)(nil), (*ICSMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineTemplateResource_To_v1alpha4_ICSMachineTemplateResource(a.(*v1beta1.ICSMachineTemplateResource), b.(*ICSMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSMachineTemplateSpec)(nil), (*v1beta1.ICSMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSMachineTemplateSpec_To_v1beta1_ICSMachineTemplateSpec(a.(*ICSMachineTemplateSpec), b.(*v1beta1.ICSMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSMachineTemplateSpec)(nil), (*ICSMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSMachineTemplateSpec_To_v1alpha4_ICSMachineTemplateSpec(a.(*v1beta1.ICSMachineTemplateSpec), b.(*ICSMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSVM)(nil), (*v1beta1.ICSVM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSVM_To_v1beta1_ICSVM(a.(*ICSVM), b.(*v1beta1.ICSVM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSVM)(nil), (*ICSVM)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSVM_To_v1alpha4_ICSVM(a.(*v1beta1.ICSVM), b.(*ICSVM), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSVMList)(nil), (*v1beta1.ICSVMList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSVMList_To_v1beta1_ICSVMList(a.(*ICSVMList), b.(*v1beta1.ICSVMList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSVMList)(nil), (*ICSVMList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSVMList_To_v1alpha4_ICSVMList(a.(*v1beta1.ICSVMList), b.(*ICSVMList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSVMSpec)(nil), (*v1beta1.ICSVMSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSVMSpec_To_v1beta1_ICSVMSpec(a.(*ICSVMSpec), b.(*v1beta1.ICSVMSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSVMSpec)(nil), (*ICSVMSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSVMSpec_To_v1alpha4_ICSVMSpec(a.(*v1beta1.ICSVMSpec), b.(*ICSVMSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ICSVMStatus)(nil), (*v1beta1.ICSVMStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ICSVMStatus_To_v1beta1_ICSVMStatus(a.(*ICSVMStatus), b.(*v1beta1.ICSVMStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ICSVMStatus)(nil), (*ICSVMStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ICSVMStatus_To_v1alpha4_ICSVMStatus(a.(*v1beta1.ICSVMStatus), b.(*ICSVMStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPAddress)(nil), (*v1beta1.IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IPAddress_To_v1beta1_IPAddress(a.(*IPAddress), b.(*v1beta1.IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IPAddress)(nil), (*IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IPAddress_To_v1alpha4_IPAddress(a.(*v1beta1.IPAddress), b.(*IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPAddressList)(nil), (*v1beta1.IPAddressList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IPAddressList_To_v1beta1_IPAddressList(a.(*IPAddressList), b.(*v1beta1.IPAddressList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IPAddressList)(nil), (*IPAddressList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IPAddressList_To_v1alpha4_IPAddressList(a.(*v1beta1.IPAddressList), b.(*IPAddressList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPAddressSpec)(nil), (*v1beta1.IPAddressSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_IPAddressSpec_To_v1beta1_IPAddressSpec(a.(*IPAddressSpec), b.(*v1beta1.IPAddressSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IPAddressSpec)(nil), (*IPAddressSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IPAddressSpec_To_v1alpha4_IPAddressSpec(a.(*v1beta1.IPAddressSpec), b.(*IPAddressSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkDeviceSpec)(nil), (*v1beta1.NetworkDeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkDeviceSpec_To_v1beta1_NetworkDeviceSpec(a.(*NetworkDeviceSpec), b.(*v1beta1.NetworkDeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkDeviceSpec)(nil), (*NetworkDeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkDeviceSpec_To_v1alpha4_NetworkDeviceSpec(a.(*v1beta1.NetworkDeviceSpec), b.(*NetworkDeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkRouteSpec)(nil), (*v1beta1.NetworkRouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkRouteSpec_To_v1beta1_NetworkRouteSpec(a.(*NetworkRouteSpec), b.(*v1beta1.NetworkRouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkRouteSpec)(nil), (*NetworkRouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkRouteSpec_To_v1alpha4_NetworkRouteSpec(a.(*v1beta1.NetworkRouteSpec), b.(*NetworkRouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1beta1.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(a.(*NetworkSpec), b.(*v1beta1.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(a.(*v1beta1.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*v1beta1.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_NetworkStatus_To_v1beta1_NetworkStatus(a.(*NetworkStatus), b.(*v1beta1.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkStatus_To_v1alpha4_NetworkStatus(a.(*v1beta1.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SSHUser)(nil), (*v1beta1.SSHUser)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_SSHUser_To_v1beta1_SSHUser(a.(*SSHUser), b.(*v1beta1.SSHUser), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SSHUser)(nil), (*SSHUser)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SSHUser_To_v1alpha4_SSHUser(a.(*v1beta1.SSHUser), b.(*SSHUser), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*v1beta1.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VirtualMachine_To_v1beta1_VirtualMachine(a.(*VirtualMachine), b.(*v1beta1.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachine_To_v1alpha4_VirtualMachine(a.(*v1beta1.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineCloneSpec)(nil), (*v1beta1.VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec(a.(*VirtualMachineCloneSpec), b.(*v1beta1.VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VirtualMachineCloneSpec)(nil), (*VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec(a.(*v1beta1.VirtualMachineCloneSpec), b.(*VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha4.ObjectMeta)(nil), (*apiv1beta1.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_ObjectMeta_To_v1beta1_ObjectMeta(a.(*apiv1alpha4.ObjectMeta), b.(*apiv1beta1.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta1.ObjectMeta)(nil), (*apiv1alpha4.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ObjectMeta_To_v1alpha4_ObjectMeta(a.(*apiv1beta1.ObjectMeta), b.(*apiv1alpha4.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha4_ClusterModule_To_v1beta1_ClusterModule(in *ClusterModule, out *v1beta1.ClusterModule, s conversion.Scope) error {
	out.ControlPlane = in.ControlPlane
	out.TargetObjectName = in.TargetObjectName
	out.ModuleUUID = in.ModuleUUID
	return nil
}

// Convert_v1alpha4_ClusterModule_To_v1beta1_ClusterModule is an autogenerated conversion function.
func Convert_v1alpha4_ClusterModule_To_v1beta1_ClusterModule(in *ClusterModule, out *v1beta1.ClusterModule, s conversion.Scope) error {
	return autoConvert_v1alpha4_ClusterModule_To_v1beta1_ClusterModule(in, out, s)
}

func autoConvert_v1beta1_ClusterModule_To_v1alpha4_ClusterModule(in *v1beta1.ClusterModule, out *ClusterModule, s conversion.Scope) error {
	out.ControlPlane = in.ControlPlane
	out.TargetObjectName = in.TargetObjectName
	out.ModuleUUID = in.ModuleUUID
	return nil
}

// Convert_v1beta1_ClusterModule_To_v1alpha4_ClusterModule is an autogenerated conversion function.
func Convert_v1beta1_ClusterModule_To_v1alpha4_ClusterModule(in *v1beta1.ClusterModule, out *ClusterModule, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterModule_To_v1alpha4_ClusterModule(in, out, s)
}

func autoConvert_v1alpha4_DiskSpec_To_v1beta1_DiskSpec(in *DiskSpec, out *v1beta1.DiskSpec, s conversion.Scope) error {
	out.DiskSize = in.DiskSize
	out.BusModel = in.BusModel
	out.VolumeFormat = in.VolumeFormat
	out.VolumePolicy = in.VolumePolicy
	return nil
}

// Convert_v1alpha4_DiskSpec_To_v1beta1_DiskSpec is an autogenerated conversion function.
func Convert_v1alpha4_DiskSpec_To_v1beta1_DiskSpec(in *DiskSpec, out *v1beta1.DiskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_DiskSpec_To_v1beta1_DiskSpec(in, out, s)
}

func autoConvert_v1beta1_DiskSpec_To_v1alpha4_DiskSpec(in *v1beta1.DiskSpec, out *DiskSpec, s conversion.Scope) error {
	out.DiskSize = in.DiskSize
	out.BusModel = in.BusModel
	out.VolumeFormat = in.VolumeFormat
	out.VolumePolicy = in.VolumePolicy
	return nil
}

// Convert_v1beta1_DiskSpec_To_v1alpha4_DiskSpec is an autogenerated conversion function.
func Convert_v1beta1_DiskSpec_To_v1alpha4_DiskSpec(in *v1beta1.DiskSpec, out *DiskSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DiskSpec_To_v1alpha4_DiskSpec(in, out, s)
}

func autoConvert_v1alpha4_ICSCluster_To_v1beta1_ICSCluster(in *ICSCluster, out *v1beta1.ICSCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_ICSClusterSpec_To_v1beta1_ICSClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_ICSClusterStatus_To_v1beta1_ICSClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ICSCluster_To_v1beta1_ICSCluster is an autogenerated conversion function.
func Convert_v1alpha4_ICSCluster_To_v1beta1_ICSCluster(in *ICSCluster, out *v1beta1.ICSCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSCluster_To_v1beta1_ICSCluster(in, out, s)
}

func autoConvert_v1beta1_ICSCluster_To_v1alpha4_ICSCluster(in *v1beta1.ICSCluster, out *ICSCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ICSClusterSpec_To_v1alpha4_ICSClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ICSClusterStatus_To_v1alpha4_ICSClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ICSCluster_To_v1alpha4_ICSCluster is an autogenerated conversion function.
func Convert_v1beta1_ICSCluster_To_v1alpha4_ICSCluster(in *v1beta1.ICSCluster, out *ICSCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSCluster_To_v1alpha4_ICSCluster(in, out, s)
}

func autoConvert_v1alpha4_ICSClusterList_To_v1beta1_ICSClusterList(in *ICSClusterList, out *v1beta1.ICSClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ICSCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_ICSClusterList_To_v1beta1_ICSClusterList is an autogenerated conversion function.
func Convert_v1alpha4_ICSClusterList_To_v1beta1_ICSClusterList(in *ICSClusterList, out *v1beta1.ICSClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSClusterList_To_v1beta1_ICSClusterList(in, out, s)
}

func autoConvert_v1beta1_ICSClusterList_To_v1alpha4_ICSClusterList(in *v1beta1.ICSClusterList, out *ICSClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ICSCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ICSClusterList_To_v1alpha4_ICSClusterList is an autogenerated conversion function.
func Convert_v1beta1_ICSClusterList_To_v1alpha4_ICSClusterList(in *v1beta1.ICSClusterList, out *ICSClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSClusterList_To_v1alpha4_ICSClusterList(in, out, s)
}

func autoConvert_v1alpha4_ICSClusterSpec_To_v1beta1_ICSClusterSpec(in *ICSClusterSpec, out *v1beta1.ICSClusterSpec, s conversion.Scope) error {
	out.CloudName = in.CloudName
	out.IdentityRef = (*v1beta1.ICSIdentityReference)(unsafe.Pointer(in.IdentityRef))
	out.Insecure = (*bool)(unsafe.Pointer(in.Insecure))
	out.EnabledLoadBalancer = in.EnabledLoadBalancer
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.ClusterModules = *(*[]v1beta1.ClusterModule)(unsafe.Pointer(&in.ClusterModules))
	return nil
}

// Convert_v1alpha4_ICSClusterSpec_To_v1beta1_ICSClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_ICSClusterSpec_To_v1beta1_ICSClusterSpec(in *ICSClusterSpec, out *v1beta1.ICSClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSClusterSpec_To_v1beta1_ICSClusterSpec(in, out, s)
}

func autoConvert_v1beta1_ICSClusterSpec_To_v1alpha4_ICSClusterSpec(in *v1beta1.ICSClusterSpec, out *ICSClusterSpec, s conversion.Scope) error {
	out.CloudName = in.CloudName
	out.IdentityRef = (*ICSIdentityReference)(unsafe.Pointer(in.IdentityRef))
	out.Insecure = (*bool)(unsafe.Pointer(in.Insecure))
	out.EnabledLoadBalancer = in.EnabledLoadBalancer
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.ClusterModules = *(*[]ClusterModule)(unsafe.Pointer(&in.ClusterModules))
	return nil
}

// Convert_v1beta1_ICSClusterSpec_To_v1alpha4_ICSClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_ICSClusterSpec_To_v1alpha4_ICSClusterSpec(in *v1beta1.ICSClusterSpec, out *ICSClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSClusterSpec_To_v1alpha4_ICSClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_ICSClusterStatus_To_v1beta1_ICSClusterStatus(in *ICSClusterStatus, out *v1beta1.ICSClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ICenterVersion = v1beta1.ICenterVersion(in.ICenterVersion)
	return nil
}

// Convert_v1alpha4_ICSClusterStatus_To_v1beta1_ICSClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_ICSClusterStatus_To_v1beta1_ICSClusterStatus(in *ICSClusterStatus, out *v1beta1.ICSClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSClusterStatus_To_v1beta1_ICSClusterStatus(in, out, s)
}

func autoConvert_v1beta1_ICSClusterStatus_To_v1alpha4_ICSClusterStatus(in *v1beta1.ICSClusterStatus, out *ICSClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ICenterVersion = ICenterVersion(in.ICenterVersion)
	return nil
}

// Convert_v1beta1_ICSClusterStatus_To_v1alpha4_ICSClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_ICSClusterStatus_To_v1alpha4_ICSClusterStatus(in *v1beta1.ICSClusterStatus, out *ICSClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSClusterStatus_To_v1alpha4_ICSClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_ICSIdentityReference_To_v1beta1_ICSIdentityReference(in *ICSIdentityReference, out *v1beta1.ICSIdentityReference, s conversion.Scope) error {
	out.Kind = v1beta1.ICSIdentityKind(in.Kind)
	out.Name = in.Name
	out.IdentityKey = (*string)(unsafe.Pointer(in.IdentityKey))
	return nil
}

// Convert_v1alpha4_ICSIdentityReference_To_v1beta1_ICSIdentityReference is an autogenerated conversion function.
func Convert_v1alpha4_ICSIdentityReference_To_v1beta1_ICSIdentityReference(in *ICSIdentityReference, out *v1beta1.ICSIdentityReference, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSIdentityReference_To_v1beta1_ICSIdentityReference(in, out, s)
}

func autoConvert_v1beta1_ICSIdentityReference_To_v1alpha4_ICSIdentityReference(in *v1beta1.ICSIdentityReference, out *ICSIdentityReference, s conversion.Scope) error {
	out.Kind = ICSIdentityKind(in.Kind)
	out.Name = in.Name
	out.IdentityKey = (*string)(unsafe.Pointer(in.IdentityKey))
	return nil
}

// Convert_v1beta1_ICSIdentityReference_To_v1alpha4_ICSIdentityReference is an autogenerated conversion function.
func Convert_v1beta1_ICSIdentityReference_To_v1alpha4_ICSIdentityReference(in *v1beta1.ICSIdentityReference, out *ICSIdentityReference, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSIdentityReference_To_v1alpha4_ICSIdentityReference(in, out, s)
}

func autoConvert_v1alpha4_ICSMachine_To_v1beta1_ICSMachine(in *ICSMachine, out *v1beta1.ICSMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_ICSMachineStatus_To_v1beta1_ICSMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ICSMachine_To_v1beta1_ICSMachine is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachine_To_v1beta1_ICSMachine(in *ICSMachine, out *v1beta1.ICSMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachine_To_v1beta1_ICSMachine(in, out, s)
}

func autoConvert_v1beta1_ICSMachine_To_v1alpha4_ICSMachine(in *v1beta1.ICSMachine, out *ICSMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ICSMachineStatus_To_v1alpha4_ICSMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ICSMachine_To_v1alpha4_ICSMachine is an autogenerated conversion function.
func Convert_v1beta1_ICSMachine_To_v1alpha4_ICSMachine(in *v1beta1.ICSMachine, out *ICSMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachine_To_v1alpha4_ICSMachine(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineList_To_v1beta1_ICSMachineList(in *ICSMachineList, out *v1beta1.ICSMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ICSMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_ICSMachineList_To_v1beta1_ICSMachineList is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineList_To_v1beta1_ICSMachineList(in *ICSMachineList, out *v1beta1.ICSMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineList_To_v1beta1_ICSMachineList(in, out, s)
}

func autoConvert_v1beta1_ICSMachineList_To_v1alpha4_ICSMachineList(in *v1beta1.ICSMachineList, out *ICSMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ICSMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ICSMachineList_To_v1alpha4_ICSMachineList is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineList_To_v1alpha4_ICSMachineList(in *v1beta1.ICSMachineList, out *ICSMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineList_To_v1alpha4_ICSMachineList(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec(in *ICSMachineSpec, out *v1beta1.ICSMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	return nil
}

// Convert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec(in *ICSMachineSpec, out *v1beta1.ICSMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec(in, out, s)
}

func autoConvert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec(in *v1beta1.ICSMachineSpec, out *ICSMachineSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	return nil
}

// Convert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec(in *v1beta1.ICSMachineSpec, out *ICSMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineStatus_To_v1beta1_ICSMachineStatus(in *ICSMachineStatus, out *v1beta1.ICSMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]apiv1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.Network = *(*[]v1beta1.NetworkStatus)(unsafe.Pointer(&in.Network))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha4_ICSMachineStatus_To_v1beta1_ICSMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineStatus_To_v1beta1_ICSMachineStatus(in *ICSMachineStatus, out *v1beta1.ICSMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineStatus_To_v1beta1_ICSMachineStatus(in, out, s)
}

func autoConvert_v1beta1_ICSMachineStatus_To_v1alpha4_ICSMachineStatus(in *v1beta1.ICSMachineStatus, out *ICSMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]apiv1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_ICSMachineStatus_To_v1alpha4_ICSMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineStatus_To_v1alpha4_ICSMachineStatus(in *v1beta1.ICSMachineStatus, out *ICSMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineStatus_To_v1alpha4_ICSMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineTemplate_To_v1beta1_ICSMachineTemplate(in *ICSMachineTemplate, out *v1beta1.ICSMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_ICSMachineTemplateSpec_To_v1beta1_ICSMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ICSMachineTemplate_To_v1beta1_ICSMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineTemplate_To_v1beta1_ICSMachineTemplate(in *ICSMachineTemplate, out *v1beta1.ICSMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineTemplate_To_v1beta1_ICSMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_ICSMachineTemplate_To_v1alpha4_ICSMachineTemplate(in *v1beta1.ICSMachineTemplate, out *ICSMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ICSMachineTemplateSpec_To_v1alpha4_ICSMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ICSMachineTemplate_To_v1alpha4_ICSMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineTemplate_To_v1alpha4_ICSMachineTemplate(in *v1beta1.ICSMachineTemplate, out *ICSMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineTemplate_To_v1alpha4_ICSMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineTemplateList_To_v1beta1_ICSMachineTemplateList(in *ICSMachineTemplateList, out *v1beta1.ICSMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ICSMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_ICSMachineTemplateList_To_v1beta1_ICSMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineTemplateList_To_v1beta1_ICSMachineTemplateList(in *ICSMachineTemplateList, out *v1beta1.ICSMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineTemplateList_To_v1beta1_ICSMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_ICSMachineTemplateList_To_v1alpha4_ICSMachineTemplateList(in *v1beta1.ICSMachineTemplateList, out *ICSMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ICSMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ICSMachineTemplateList_To_v1alpha4_ICSMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineTemplateList_To_v1alpha4_ICSMachineTemplateList(in *v1beta1.ICSMachineTemplateList, out *ICSMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineTemplateList_To_v1alpha4_ICSMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineTemplateResource_To_v1beta1_ICSMachineTemplateResource(in *ICSMachineTemplateResource, out *v1beta1.ICSMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_ICSMachineSpec_To_v1beta1_ICSMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ICSMachineTemplateResource_To_v1beta1_ICSMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineTemplateResource_To_v1beta1_ICSMachineTemplateResource(in *ICSMachineTemplateResource, out *v1beta1.ICSMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineTemplateResource_To_v1beta1_ICSMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_ICSMachineTemplateResource_To_v1alpha4_ICSMachineTemplateResource(in *v1beta1.ICSMachineTemplateResource, out *ICSMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_ICSMachineSpec_To_v1alpha4_ICSMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ICSMachineTemplateResource_To_v1alpha4_ICSMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineTemplateResource_To_v1alpha4_ICSMachineTemplateResource(in *v1beta1.ICSMachineTemplateResource, out *ICSMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineTemplateResource_To_v1alpha4_ICSMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_ICSMachineTemplateSpec_To_v1beta1_ICSMachineTemplateSpec(in *ICSMachineTemplateSpec, out *v1beta1.ICSMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_ICSMachineTemplateResource_To_v1beta1_ICSMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ICSMachineTemplateSpec_To_v1beta1_ICSMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_ICSMachineTemplateSpec_To_v1beta1_ICSMachineTemplateSpec(in *ICSMachineTemplateSpec, out *v1beta1.ICSMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSMachineTemplateSpec_To_v1beta1_ICSMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_ICSMachineTemplateSpec_To_v1alpha4_ICSMachineTemplateSpec(in *v1beta1.ICSMachineTemplateSpec, out *ICSMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_ICSMachineTemplateResource_To_v1alpha4_ICSMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ICSMachineTemplateSpec_To_v1alpha4_ICSMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_ICSMachineTemplateSpec_To_v1alpha4_ICSMachineTemplateSpec(in *v1beta1.ICSMachineTemplateSpec, out *ICSMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSMachineTemplateSpec_To_v1alpha4_ICSMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_ICSVM_To_v1beta1_ICSVM(in *ICSVM, out *v1beta1.ICSVM, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_ICSVMSpec_To_v1beta1_ICSVMSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_ICSVMStatus_To_v1beta1_ICSVMStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_ICSVM_To_v1beta1_ICSVM is an autogenerated conversion function.
func Convert_v1alpha4_ICSVM_To_v1beta1_ICSVM(in *ICSVM, out *v1beta1.ICSVM, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSVM_To_v1beta1_ICSVM(in, out, s)
}

func autoConvert_v1beta1_ICSVM_To_v1alpha4_ICSVM(in *v1beta1.ICSVM, out *ICSVM, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ICSVMSpec_To_v1alpha4_ICSVMSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ICSVMStatus_To_v1alpha4_ICSVMStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ICSVM_To_v1alpha4_ICSVM is an autogenerated conversion function.
func Convert_v1beta1_ICSVM_To_v1alpha4_ICSVM(in *v1beta1.ICSVM, out *ICSVM, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSVM_To_v1alpha4_ICSVM(in, out, s)
}

func autoConvert_v1alpha4_ICSVMList_To_v1beta1_ICSVMList(in *ICSVMList, out *v1beta1.ICSVMList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ICSVM)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_ICSVMList_To_v1beta1_ICSVMList is an autogenerated conversion function.
func Convert_v1alpha4_ICSVMList_To_v1beta1_ICSVMList(in *ICSVMList, out *v1beta1.ICSVMList, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSVMList_To_v1beta1_ICSVMList(in, out, s)
}

func autoConvert_v1beta1_ICSVMList_To_v1alpha4_ICSVMList(in *v1beta1.ICSVMList, out *ICSVMList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ICSVM)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ICSVMList_To_v1alpha4_ICSVMList is an autogenerated conversion function.
func Convert_v1beta1_ICSVMList_To_v1alpha4_ICSVMList(in *v1beta1.ICSVMList, out *ICSVMList, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSVMList_To_v1alpha4_ICSVMList(in, out, s)
}

func autoConvert_v1alpha4_ICSVMSpec_To_v1beta1_ICSVMSpec(in *ICSVMSpec, out *v1beta1.ICSVMSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.BootstrapRef = (*v1.ObjectReference)(unsafe.Pointer(in.BootstrapRef))
	out.BiosUUID = in.BiosUUID
	out.UID = in.UID
	return nil
}

// Convert_v1alpha4_ICSVMSpec_To_v1beta1_ICSVMSpec is an autogenerated conversion function.
func Convert_v1alpha4_ICSVMSpec_To_v1beta1_ICSVMSpec(in *ICSVMSpec, out *v1beta1.ICSVMSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSVMSpec_To_v1beta1_ICSVMSpec(in, out, s)
}

func autoConvert_v1beta1_ICSVMSpec_To_v1alpha4_ICSVMSpec(in *v1beta1.ICSVMSpec, out *ICSVMSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.BootstrapRef = (*v1.ObjectReference)(unsafe.Pointer(in.BootstrapRef))
	out.BiosUUID = in.BiosUUID
	out.UID = in.UID
	return nil
}

// Convert_v1beta1_ICSVMSpec_To_v1alpha4_ICSVMSpec is an autogenerated conversion function.
func Convert_v1beta1_ICSVMSpec_To_v1alpha4_ICSVMSpec(in *v1beta1.ICSVMSpec, out *ICSVMSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSVMSpec_To_v1alpha4_ICSVMSpec(in, out, s)
}

func autoConvert_v1alpha4_ICSVMStatus_To_v1beta1_ICSVMStatus(in *ICSVMStatus, out *v1beta1.ICSVMStatus, s conversion.Scope) error {
	out.Host = in.Host
	out.Ready = in.Ready
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.CloneMode = v1beta1.CloneMode(in.CloneMode)
	out.Snapshot = in.Snapshot
	out.TaskRef = in.TaskRef
	out.Network = *(*[]v1beta1.NetworkStatus)(unsafe.Pointer(&in.Network))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ModuleUUID = (*string)(unsafe.Pointer(in.ModuleUUID))
	return nil
}

// Convert_v1alpha4_ICSVMStatus_To_v1beta1_ICSVMStatus is an autogenerated conversion function.
func Convert_v1alpha4_ICSVMStatus_To_v1beta1_ICSVMStatus(in *ICSVMStatus, out *v1beta1.ICSVMStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_ICSVMStatus_To_v1beta1_ICSVMStatus(in, out, s)
}

func autoConvert_v1beta1_ICSVMStatus_To_v1alpha4_ICSVMStatus(in *v1beta1.ICSVMStatus, out *ICSVMStatus, s conversion.Scope) error {
	out.Host = in.Host
	out.Ready = in.Ready
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.CloneMode = CloneMode(in.CloneMode)
	out.Snapshot = in.Snapshot
	out.TaskRef = in.TaskRef
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ModuleUUID = (*string)(unsafe.Pointer(in.ModuleUUID))
	return nil
}

// Convert_v1beta1_ICSVMStatus_To_v1alpha4_ICSVMStatus is an autogenerated conversion function.
func Convert_v1beta1_ICSVMStatus_To_v1alpha4_ICSVMStatus(in *v1beta1.ICSVMStatus, out *ICSVMStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ICSVMStatus_To_v1alpha4_ICSVMStatus(in, out, s)
}

func autoConvert_v1alpha4_IPAddress_To_v1beta1_IPAddress(in *IPAddress, out *v1beta1.IPAddress, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_IPAddressSpec_To_v1beta1_IPAddressSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_IPAddress_To_v1beta1_IPAddress is an autogenerated conversion function.
func Convert_v1alpha4_IPAddress_To_v1beta1_IPAddress(in *IPAddress, out *v1beta1.IPAddress, s conversion.Scope) error {
	return autoConvert_v1alpha4_IPAddress_To_v1beta1_IPAddress(in, out, s)
}

func autoConvert_v1beta1_IPAddress_To_v1alpha4_IPAddress(in *v1beta1.IPAddress, out *IPAddress, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_IPAddressSpec_To_v1alpha4_IPAddressSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IPAddress_To_v1alpha4_IPAddress is an autogenerated conversion function.
func Convert_v1beta1_IPAddress_To_v1alpha4_IPAddress(in *v1beta1.IPAddress, out *IPAddress, s conversion.Scope) error {
	return autoConvert_v1beta1_IPAddress_To_v1alpha4_IPAddress(in, out, s)
}

func autoConvert_v1alpha4_IPAddressList_To_v1beta1_IPAddressList(in *IPAddressList, out *v1beta1.IPAddressList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.IPAddress)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_IPAddressList_To_v1beta1_IPAddressList is an autogenerated conversion function.
func Convert_v1alpha4_IPAddressList_To_v1beta1_IPAddressList(in *IPAddressList, out *v1beta1.IPAddressList, s conversion.Scope) error {
	return autoConvert_v1alpha4_IPAddressList_To_v1beta1_IPAddressList(in, out, s)
}

func autoConvert_v1beta1_IPAddressList_To_v1alpha4_IPAddressList(in *v1beta1.IPAddressList, out *IPAddressList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IPAddress)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_IPAddressList_To_v1alpha4_IPAddressList is an autogenerated conversion function.
func Convert_v1beta1_IPAddressList_To_v1alpha4_IPAddressList(in *v1beta1.IPAddressList, out *IPAddressList, s conversion.Scope) error {
	return autoConvert_v1beta1_IPAddressList_To_v1alpha4_IPAddressList(in, out, s)
}

func autoConvert_v1alpha4_IPAddressSpec_To_v1beta1_IPAddressSpec(in *IPAddressSpec, out *v1beta1.IPAddressSpec, s conversion.Scope) error {
	out.VMRef = in.VMRef
	out.TemplateRef = in.TemplateRef
	out.Prefix = in.Prefix
	out.Gateway = (*string)(unsafe.Pointer(in.Gateway))
	out.Address = in.Address
	out.MACAddr = in.MACAddr
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	return nil
}

// Convert_v1alpha4_IPAddressSpec_To_v1beta1_IPAddressSpec is an autogenerated conversion function.
func Convert_v1alpha4_IPAddressSpec_To_v1beta1_IPAddressSpec(in *IPAddressSpec, out *v1beta1.IPAddressSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_IPAddressSpec_To_v1beta1_IPAddressSpec(in, out, s)
}

func autoConvert_v1beta1_IPAddressSpec_To_v1alpha4_IPAddressSpec(in *v1beta1.IPAddressSpec, out *IPAddressSpec, s conversion.Scope) error {
	out.VMRef = in.VMRef
	out.TemplateRef = in.TemplateRef
	out.Prefix = in.Prefix
	out.Gateway = (*string)(unsafe.Pointer(in.Gateway))
	out.Address = in.Address
	out.MACAddr = in.MACAddr
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	return nil
}

// Convert_v1beta1_IPAddressSpec_To_v1alpha4_IPAddressSpec is an autogenerated conversion function.
func Convert_v1beta1_IPAddressSpec_To_v1alpha4_IPAddressSpec(in *v1beta1.IPAddressSpec, out *IPAddressSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_IPAddressSpec_To_v1alpha4_IPAddressSpec(in, out, s)
}

func autoConvert_v1alpha4_NetworkDeviceSpec_To_v1beta1_NetworkDeviceSpec(in *NetworkDeviceSpec, out *v1beta1.NetworkDeviceSpec, s conversion.Scope) error {
	out.SwitchType = in.SwitchType
	out.NetworkID = in.NetworkID
	out.NetworkName = in.NetworkName
	out.NetworkType = in.NetworkType
	out.DeviceID = in.DeviceID
	out.DeviceName = in.DeviceName
	out.DHCP4 = in.DHCP4
	out.DHCP6 = in.DHCP6
	out.NetMask = in.NetMask
	out.Gateway4 = in.Gateway4
	out.Gateway6 = in.Gateway6
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MTU = (*int64)(unsafe.Pointer(in.MTU))
	out.MACAddr = in.MACAddr
	out.Nameservers = *(*[]string)(unsafe.Pointer(&in.Nameservers))
	out.Routes = *(*[]v1beta1.NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.SearchDomains = *(*[]string)(unsafe.Pointer(&in.SearchDomains))
	return nil
}

// Convert_v1alpha4_NetworkDeviceSpec_To_v1beta1_NetworkDeviceSpec is an autogenerated conversion function.
func Convert_v1alpha4_NetworkDeviceSpec_To_v1beta1_NetworkDeviceSpec(in *NetworkDeviceSpec, out *v1beta1.NetworkDeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkDeviceSpec_To_v1beta1_NetworkDeviceSpec(in, out, s)
}

func autoConvert_v1beta1_NetworkDeviceSpec_To_v1alpha4_NetworkDeviceSpec(in *v1beta1.NetworkDeviceSpec, out *NetworkDeviceSpec, s conversion.Scope) error {
	out.SwitchType = in.SwitchType
	out.NetworkID = in.NetworkID
	out.NetworkName = in.NetworkName
	out.NetworkType = in.NetworkType
	out.DeviceID = in.DeviceID
	out.DeviceName = in.DeviceName
	out.DHCP4 = in.DHCP4
	out.DHCP6 = in.DHCP6
	out.NetMask = in.NetMask
	out.Gateway4 = in.Gateway4
	out.Gateway6 = in.Gateway6
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MTU = (*int64)(unsafe.Pointer(in.MTU))
	out.MACAddr = in.MACAddr
	out.Nameservers = *(*[]string)(unsafe.Pointer(&in.Nameservers))
	out.Routes = *(*[]NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.SearchDomains = *(*[]string)(unsafe.Pointer(&in.SearchDomains))
	return nil
}

// Convert_v1beta1_NetworkDeviceSpec_To_v1alpha4_NetworkDeviceSpec is an autogenerated conversion function.
func Convert_v1beta1_NetworkDeviceSpec_To_v1alpha4_NetworkDeviceSpec(in *v1beta1.NetworkDeviceSpec, out *NetworkDeviceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkDeviceSpec_To_v1alpha4_NetworkDeviceSpec(in, out, s)
}

func autoConvert_v1alpha4_NetworkRouteSpec_To_v1beta1_NetworkRouteSpec(in *NetworkRouteSpec, out *v1beta1.NetworkRouteSpec, s conversion.Scope) error {
	out.To = in.To
	out.Via = in.Via
	out.Metric = in.Metric
	return nil
}

// Convert_v1alpha4_NetworkRouteSpec_To_v1beta1_NetworkRouteSpec is an autogenerated conversion function.
func Convert_v1alpha4_NetworkRouteSpec_To_v1beta1_NetworkRouteSpec(in *NetworkRouteSpec, out *v1beta1.NetworkRouteSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkRouteSpec_To_v1beta1_NetworkRouteSpec(in, out, s)
}

func autoConvert_v1beta1_NetworkRouteSpec_To_v1alpha4_NetworkRouteSpec(in *v1beta1.NetworkRouteSpec, out *NetworkRouteSpec, s conversion.Scope) error {
	out.To = in.To
	out.Via = in.Via
	out.Metric = in.Metric
	return nil
}

// Convert_v1beta1_NetworkRouteSpec_To_v1alpha4_NetworkRouteSpec is an autogenerated conversion function.
func Convert_v1beta1_NetworkRouteSpec_To_v1alpha4_NetworkRouteSpec(in *v1beta1.NetworkRouteSpec, out *NetworkRouteSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkRouteSpec_To_v1alpha4_NetworkRouteSpec(in, out, s)
}

func autoConvert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(in *NetworkSpec, out *v1beta1.NetworkSpec, s conversion.Scope) error {
	out.Devices = *(*[]v1beta1.NetworkDeviceSpec)(unsafe.Pointer(&in.Devices))
	out.Routes = *(*[]v1beta1.NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.PreferredAPIServerCIDR = in.PreferredAPIServerCIDR
	return nil
}

// Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(in *NetworkSpec, out *v1beta1.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(in, out, s)
}

func autoConvert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(in *v1beta1.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	out.Devices = *(*[]NetworkDeviceSpec)(unsafe.Pointer(&in.Devices))
	out.Routes = *(*[]NetworkRouteSpec)(unsafe.Pointer(&in.Routes))
	out.PreferredAPIServerCIDR = in.PreferredAPIServerCIDR
	return nil
}

// Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec is an autogenerated conversion function.
func Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(in *v1beta1.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha4_NetworkStatus_To_v1beta1_NetworkStatus(in *NetworkStatus, out *v1beta1.NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha4_NetworkStatus_To_v1beta1_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha4_NetworkStatus_To_v1beta1_NetworkStatus(in *NetworkStatus, out *v1beta1.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_NetworkStatus_To_v1beta1_NetworkStatus(in, out, s)
}

func autoConvert_v1beta1_NetworkStatus_To_v1alpha4_NetworkStatus(in *v1beta1.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1beta1_NetworkStatus_To_v1alpha4_NetworkStatus is an autogenerated conversion function.
func Convert_v1beta1_NetworkStatus_To_v1alpha4_NetworkStatus(in *v1beta1.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkStatus_To_v1alpha4_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha4_SSHUser_To_v1beta1_SSHUser(in *SSHUser, out *v1beta1.SSHUser, s conversion.Scope) error {
	out.Name = in.Name
	out.AuthorizedType = v1beta1.AuthorizedMode(in.AuthorizedType)
	out.AuthorizedKey = in.AuthorizedKey
	return nil
}

// Convert_v1alpha4_SSHUser_To_v1beta1_SSHUser is an autogenerated conversion function.
func Convert_v1alpha4_SSHUser_To_v1beta1_SSHUser(in *SSHUser, out *v1beta1.SSHUser, s conversion.Scope) error {
	return autoConvert_v1alpha4_SSHUser_To_v1beta1_SSHUser(in, out, s)
}

func autoConvert_v1beta1_SSHUser_To_v1alpha4_SSHUser(in *v1beta1.SSHUser, out *SSHUser, s conversion.Scope) error {
	out.Name = in.Name
	out.AuthorizedType = AuthorizedMode(in.AuthorizedType)
	out.AuthorizedKey = in.AuthorizedKey
	return nil
}

// Convert_v1beta1_SSHUser_To_v1alpha4_SSHUser is an autogenerated conversion function.
func Convert_v1beta1_SSHUser_To_v1alpha4_SSHUser(in *v1beta1.SSHUser, out *SSHUser, s conversion.Scope) error {
	return autoConvert_v1beta1_SSHUser_To_v1alpha4_SSHUser(in, out, s)
}

func autoConvert_v1alpha4_VirtualMachine_To_v1beta1_VirtualMachine(in *VirtualMachine, out *v1beta1.VirtualMachine, s conversion.Scope) error {
	out.UID = in.UID
	out.Name = in.Name
	out.BiosUUID = in.BiosUUID
	out.State = v1beta1.VirtualMachineState(in.State)
	out.Network = *(*[]v1beta1.NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha4_VirtualMachine_To_v1beta1_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha4_VirtualMachine_To_v1beta1_VirtualMachine(in *VirtualMachine, out *v1beta1.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_VirtualMachine_To_v1beta1_VirtualMachine(in, out, s)
}

func autoConvert_v1beta1_VirtualMachine_To_v1alpha4_VirtualMachine(in *v1beta1.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.UID = in.UID
	out.Name = in.Name
	out.BiosUUID = in.BiosUUID
	out.State = VirtualMachineState(in.State)
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1beta1_VirtualMachine_To_v1alpha4_VirtualMachine is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachine_To_v1alpha4_VirtualMachine(in *v1beta1.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachine_To_v1alpha4_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1beta1.VirtualMachineCloneSpec, s conversion.Scope) error {
	out.CloudName = in.CloudName
	out.IdentityRef = (*v1beta1.ICSIdentityReference)(unsafe.Pointer(in.IdentityRef))
	out.Template = in.Template
	out.CloneMode = v1beta1.CloneMode(in.CloneMode)
	out.Snapshot = in.Snapshot
	out.Datacenter = in.Datacenter
	out.Cluster = in.Cluster
	out.Datastore = in.Datastore
	if err := Convert_v1alpha4_NetworkSpec_To_v1beta1_NetworkSpec(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.NumCPUs = in.NumCPUs
	out.NumCoresPerSocket = in.NumCoresPerSocket
	out.MemoryMiB = in.MemoryMiB
	out.Disks = *(*[]v1beta1.DiskSpec)(unsafe.Pointer(&in.Disks))
	out.User = (*v1beta1.SSHUser)(unsafe.Pointer(in.User))
	return nil
}

// Convert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1beta1.VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_VirtualMachineCloneSpec_To_v1beta1_VirtualMachineCloneSpec(in, out, s)
}

func autoConvert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec(in *v1beta1.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	out.CloudName = in.CloudName
	out.IdentityRef = (*ICSIdentityReference)(unsafe.Pointer(in.IdentityRef))
	out.Template = in.Template
	out.CloneMode = CloneMode(in.CloneMode)
	out.Snapshot = in.Snapshot
	out.Datacenter = in.Datacenter
	out.Cluster = in.Cluster
	out.Datastore = in.Datastore
	if err := Convert_v1beta1_NetworkSpec_To_v1alpha4_NetworkSpec(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.NumCPUs = in.NumCPUs
	out.NumCoresPerSocket = in.NumCoresPerSocket
	out.MemoryMiB = in.MemoryMiB
	out.Disks = *(*[]DiskSpec)(unsafe.Pointer(&in.Disks))
	out.User = (*SSHUser)(unsafe.Pointer(in.User))
	return nil
}

// Convert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec(in *v1beta1.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_VirtualMachineCloneSpec_To_v1alpha4_VirtualMachineCloneSpec(in, out, s)
}
